export const PATHS = {
  home: '/',
  login: '/login',
  register: '/cadastro',
  forgotPassword: '/recuperar-senha',
  onboarding: '/onboarding',
  app: '/app',
  finance: '/app/financas',
  accounts: '/app/contas',
  cards: '/app/cartoes',
  subscriptions: '/app/assinaturas',
  goals: '/app/metas',
  tasks: '/app/tarefas',
  routine: '/app/rotina',
  habits: '/app/habitos',
  documents: '/app/documentos',
  digital: '/app/organizacao-digital',
  checklists: '/app/checklists',
  challenge: '/app/desafio',
  profile: '/app/perfil',
  settings: '/app/configuracoes',
  help: '/app/ajuda',
  admin: '/admin',
} as const
